### ISSUE TITLE
Erro

### ISSUE THREAD

**Issue by Japa18244** [renatofmmaia/spacecrypto-bot#1]
Bom dia, está acontecendo esse erro sempre.

![image](https://user-images.githubusercontent.com/97619573/154842436-5489c8e9-c615-4f5a-9840-11a2b66b18b7.png)

[02-20 09:25] => Traceback (most recent call last):
  File ".\main.py", line 68, in main
    manager.do_what_needs_to_be_done(current_screen)
  File "C:\Users\richa\Desktop\spacecrypto-bot-main2\spacecrypto-bot-main\module\manager.py", line 49, in do_what_needs_to_be_done
    Ship.keep_working(self)
  File "C:\Users\richa\Desktop\spacecrypto-bot-main2\spacecrypto-bot-main\module\spaceScreen.py", line 297, in keep_working
    n_found = Ship.get_number_of_ships_in_battle(Image.screen())
  File "C:\Users\richa\Desktop\spacecrypto-bot-main2\spacecrypto-bot-main\module\spaceScreen.py", line 322, in get_number_of_ships_in_battle
    x, y, w, _ = Image.get_one_target_position("identify_n_space_shipts_in_battle", screen_image=screen_img)
  File "C:\Users\richa\Desktop\spacecrypto-bot-main2\spacecrypto-bot-main\module\image.py", line 159, in get_one_target_position
    raise Exception(f"{target} not found")
Exception: identify_n_space_shipts_in_battle not found

ele coloca uma nave e tira e fica nesse loop infinito

**Comment by rogeriojim** [comment]
Tambem estou com esse erro, ele adiciona a primeira nave e o erro acontece, não passa da primeira.

Tentei varias resoluções e tirei varias prints da minha tela, mais nao deu jeito nao.

**Comment by hiagopinacio** [comment]
@Japa18244 e @rogeriojim 
Me passa as seguintes informações pra eu tentar reproduzir:

Sistema operacional.
Resolução da tela.
Navegador.
A navegador está maximizado?
O navegador tem barra de favoritos?

**Comment by hiagopinacio** [comment]
uma possível soluçao é ir na pasta `spacecrypto-bot\assets\images\targets` e substituir o arquivo **`identify_n_space_shipts_in_battle.png`** por esta imagem:
![identify_n_space_shipts_in_battle](https://user-images.githubusercontent.com/54750249/154845130-538237b1-94f3-4702-9c1c-382f6efd54e2.png)

Me avisem se esta solução funcionar por favor.

**Comment by Japa18244** [comment]
> @Japa18244 e @rogeriojim
> 
> garanta que seguiram estes passos:
> 
> para que o bot reconheça sua resolução de tela e seja acertivo em seus comandos, você deve criar uma imagem de qualquer tela do space crypto, porém deve conter apenas a área do jogo, e salvar na pasta "assets/images/targets_global/" com o nome "screen_user.png": user_screen space_user
> 
> IMPORTANTE: Após iniciar o bot, você não pode redimensionar a tela do navegador(jogo), caso seja necessário redimensionar, você deve repetir o passo acima, criando uma nova imagem da tela do space crypto. Me passa as seguintes informações pra eu tentar reproduzir:
> 
> Caso já tenha feito isso, me passe as seguintes informações para que eu possa tentar reproduzir:
> 
> Sistema operacional. Resolução da tela. Navegador. A navegador está maximizado? O navegador tem barra de favoritos?
> 
> Nós desenvolvemos o bot em resolução full hd (1920x1080) utilizando o google chrome maximizado.
> 
> uma possível soluçao é ir na pasta `spacecrypto-bot\assets\images\targets` e substituir o arquivo **`identify_n_space_shipts_in_battle.png`** por esta imagem: ![identify_n_space_shipts_in_battle](https://user-images.githubusercontent.com/54750249/154845130-538237b1-94f3-4702-9c1c-382f6efd54e2.png)
> 
> Me avisem se esta solução funcionar por favor.

Fiz a alteração ai da imagem e deu certo, MAS deu outro erro.

[02-20 10:53] => Traceback (most recent call last):
  File "main.py", line 68, in main
    manager.do_what_needs_to_be_done(current_screen)
  File "C:\Users\richa\Desktop\spacecrypto-bot-main2\spacecrypto-bot-main\module\manager.py", line 49, in do_what_needs_to_be_done
    Ship.keep_working(self)
  File "C:\Users\richa\Desktop\spacecrypto-bot-main2\spacecrypto-bot-main\module\spaceScreen.py", line 300, in keep_working
    raise Exception(f"Error trying to send {n_ships} ships to fight. Found only {n_found}.")
Exception: Error trying to send 8 ships to fight. Found only 1.

[02-20 10:55] => Traceback (most recent call last):
  File "main.py", line 68, in main
    manager.do_what_needs_to_be_done(current_screen)
  File "C:\Users\richa\Desktop\spacecrypto-bot-main2\spacecrypto-bot-main\module\manager.py", line 49, in do_what_needs_to_be_done
    Ship.keep_working(self)
  File "C:\Users\richa\Desktop\spacecrypto-bot-main2\spacecrypto-bot-main\module\spaceScreen.py", line 300, in keep_working
    raise Exception(f"Error trying to send {n_ships} ships to fight. Found only {n_found}.")
Exception: Error trying to send 8 ships to fight. Found only 1.

ele seleciona 8 naves das 45 que eu tenho e depois tira todas as 8 novamente e fica nesse ciclo, segue erro acima.

**Comment by rogeriojim** [comment]
Vamos lá.

Tirei a foto certinha da tela do jogo.

Meu monitor usa uma resolução mais alta 2560x1080 ,   fiz o teste com a resolução recomendada 1920x1080 e tambem tive o mesmo erro com um item a mais.

Segue :

`[02-20 12:24] => Traceback (most recent call last):
  File "C:\spacecrypto-bot-main\main.py", line 68, in main
    manager.do_what_needs_to_be_done(current_screen)
  File "C:\spacecrypto-bot-main\module\manager.py", line 49, in do_what_needs_to_be_done
    Ship.keep_working(self)
  File "C:\spacecrypto-bot-main\module\spaceScreen.py", line 297, in keep_working
    n_found = Ship.get_number_of_ships_in_battle(Image.screen())
  File "C:\spacecrypto-bot-main\module\spaceScreen.py", line 333, in get_number_of_ships_in_battle
    max_index = Image.get_max_result_between(n_ships_list, screen_img=search_img)
  File "C:\spacecrypto-bot-main\module\image.py", line 178, in get_max_result_between
    result = cv2.matchTemplate(screen, Image.TARGETS[target], cv2.TM_CCOEFF_NORMED)
cv2.error: OpenCV(4.5.4) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\templmatch.cpp:1175: error: (-215:Assertion failed) _img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width in function 'cv::matchTemplate'


`

**Comment by Japa18244** [comment]
> Vamos lá.
> 
> Tirei a foto certinha da tela do jogo.
> 
> Meu monitor usa uma resolução mais alta 2560x1080 , fiz o teste com a resolução recomendada 1920x1080 e tambem tive o mesmo erro com um item a mais.
> 
> Segue :
> 
> `[02-20 12:24] => Traceback (most recent call last): File "C:\spacecrypto-bot-main\main.py", line 68, in main manager.do_what_needs_to_be_done(current_screen) File "C:\spacecrypto-bot-main\module\manager.py", line 49, in do_what_needs_to_be_done Ship.keep_working(self) File "C:\spacecrypto-bot-main\module\spaceScreen.py", line 297, in keep_working n_found = Ship.get_number_of_ships_in_battle(Image.screen()) File "C:\spacecrypto-bot-main\module\spaceScreen.py", line 333, in get_number_of_ships_in_battle max_index = Image.get_max_result_between(n_ships_list, screen_img=search_img) File "C:\spacecrypto-bot-main\module\image.py", line 178, in get_max_result_between result = cv2.matchTemplate(screen, Image.TARGETS[target], cv2.TM_CCOEFF_NORMED) cv2.error: OpenCV(4.5.4) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\templmatch.cpp:1175: error: (-215:Assertion failed) _img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width in function 'cv::matchTemplate'
> 
> `

Baixa de novo o bot @rogeriojim, eles corrigiram o erro.

**Comment by hiagopinacio** [comment]
Galera, obrigado pelo feedback. Fiz alguns ajustes nos targets e  no resize.
Baixem a versão 0.0.4.

Se persistir o erro, me avisem por favor.
