### ISSUE TITLE
Problema em configurar o Telegram

### ISSUE THREAD

**Issue by gbailinho** [renatofmmaia/spacecrypto-bot#10]
Bom dia rei, segui seu tutorial do Telegram, e nao está retornando o chat id como voce disse

![Screenshot_4](https://user-images.githubusercontent.com/99928381/154943859-df0ad576-b77f-4aca-ac80-05b14cd69bd9.png)

utilizei o https://api.telegram.org/botMEUTOKEN/getUpdates

**Comment by AbilioDade** [comment]
tenta esse,  https://api.telegram.org/bot("apaga os parenteses"token do seu bot)/getUpdates

**Comment by AbilioDade** [comment]
ex:  https://api.telegram.org/bot123456789/getUpdates

**Comment by renatofmmaia** [comment]
não esquece que precisa dar o /start no botfather

**Comment by vinepereira** [comment]
Estou com o mesmo problema da imagem kk
