### ISSUE TITLE
Ohh no! We couldn't start the bot.

### ISSUE THREAD

**Issue by felipeasgamer** [renatofmmaia/spacecrypto-bot#3]
Boa tarde Renato. 
Parabéns pelo seu trabalho excelente em nos ajudar com o bot.

Apesar de eu estar utilizando todas as configurações corretas.. aparece pra mim a seguinte msg: Ohh no! We couldn't start the bot.

poderia me ajudar
obrigado
![Captura de tela 2022-02-20 142810](https://user-images.githubusercontent.com/100088341/154855696-e9dfb693-3d81-4db1-b23a-52244e137767.png)

**Comment by felipeasgamer** [comment]
[02-20 14:43] => Traceback (most recent call last):
  File "C:\bots\spacecrypto-bot\main.py", line 28, in main
    Image.load_targets_user()
  File "C:\bots\spacecrypto-bot\module\image.py", line 41, in load_targets_user
    Image.set_images_resolution()
  File "C:\bots\spacecrypto-bot\module\image.py", line 197, in set_images_resolution
    im_user = np.array(Image.TARGETS_GLOBAL['screen_user'])
KeyError: 'screen_user'

**Comment by hiagopinacio** [comment]
Boa tarde Felipe. Como o jogo redimensiona dependendo da sua resolução, vc deve tirar uma print de referência.
Siga os passos do README: https://github.com/renatofmmaia/spacecrypto-bot#configurando-o-bot
