### ISSUE TITLE
SURRENDER

### ISSUE THREAD

**Issue by evertonurbanii** [renatofmmaia/spacecrypto-bot#4]
Boa tarde!
Primeirament, Pprabens pelo otimo trabalho!
Pela descrição não achei a função de SURRENDER em determinado BOSS, existe no roundmap o planegamento de implantação? alguma previsão?

**Comment by hiagopinacio** [comment]
Boa tarde! valeu pelo feedback!
Existe sim.
Na proxima versão queremos lançar opção de surrender e adicionar naves na base de acordo com raridade.
Provavelmente depois do withdraw.
Abçs.

**Comment by evertonurbanii** [comment]
Entendi, enquanto isso seria possivel fixar de alguma forma para ir apenas até o BOSS 6 e voltar para o 1? 
To unsado outro bot q faz isso, porém ja uso o seu de bomb e tenho muito mais confiança em vcs, sendo q as funções de raridade e % de stamina sao demais e acredito q exclusivas atualmente.

**Comment by gbailinho** [comment]
@hiagopinacio teria apenas uma projeção para essa alteração no roadmap? seria realmente interessante

**Comment by renatofmmaia** [comment]
Olá @gbailinho, estamos acompanhando ainda de perto o lançamento do bot, e ajustando possíveis problemas, queremos trazer essa função o mais breve possível :D

**Comment by filipexxborba** [comment]
@renatofmmaia acabei de lançar um PR com essa funcionalidade, se puder dar uma validada, por favor.

**Comment by gbailinho** [comment]
@filipexxborba manda pra mim!!
