### ISSUE TITLE
Sugestão - Refresh de Naves

### ISSUE THREAD

**Issue by gelbcke** [renatofmmaia/spacecrypto-bot#42]
Primeiramente, parabéns pelo desenvolvimento. 

Gostaria de sugerir que quando não tiver a quantidade suficiente de naves para mandar a luta, ao invés de remove-las e clicar em _"Fight Boss"_ e confirmar a derrota, apenas clicar em _"Base"_ e depois em _"Spaceship"_, dessa forma os valores de % de carregamento são atualizados. Pois as vezes entramos no meio da luta com um tempo bem curto.

Valeu!

**Comment by magriNbh** [comment]
cara, dessa forma vc entra em loop com várias naves paradas que foram selecionadas e não estao recarregando, ideia muito ruim. vai ficar igual os outros bots de space, no loop infinito ate achar todas as naves q vc selecionou, e se nesse meio termo o jogo tomar DC , vai bugar seu farm ;)
