### ISSUE TITLE
not searching ships?

### ISSUE THREAD

**Issue by Blackfoxx88** [renatofmmaia/spacecrypto-bot#9]
I dunno but i always encountered this 
![image](https://user-images.githubusercontent.com/99056652/154879668-8bfaaeae-6f76-4f32-aa9d-e61221a0b0c8.png)

even though i have 100% ships. it does not search it and click fight. everytime  it finds a non 100% ships it stuck to that always. =D

**Comment by renatofmmaia** [comment]
Hi @Blackfoxx88!
Possibly it's some screen resolution error, are you on version 6 of the bot?
How was your screen_user.png image?

**Comment by hiagopinacio** [comment]
Thanks for the feedback. This bug id fixed now in release 0.0.7
